spring.application.name=lumidoc

# OpenAI
open-ai.api-key={OPENAPIKEY}
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lumidoc
spring.datasource.username=postgres
spring.datasource.password=yourpassword
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB